### ISSUE TITLE
Hidden scrollbar

### ISSUE THREAD

**Issue by dopa902** [dimdenGD/BetterTweetDeck#13]
Hidden scrollbar not working as intended, shows big scrollbar no matter what. Bugg appeared in recent changes past few days/week.

- W11
- Chrome
- BTD 4.11.2

**Comment by dimdenGD** [comment]
duplicate of https://github.com/dimdenGD/BetterTweetDeck/issues/10

**Comment by dopa902** [comment]
> duplicate of #10

Got it, even though it has been working flawless for me up until a few days ago.
