### ISSUE TITLE
extension doesn't load

### ISSUE THREAD

**Issue by staticanimal** [dimdenGD/BetterTweetDeck#18]
**Describe the bug**
the extension does not load, even on a fresh install.

**To Reproduce**

1. install extension
2. load tweetdeck

**Expected behavior**
i expected the extension to load. this does not happen.

**Desktop (please complete the following information):**

- OS: Windows 11 Pro
- Browser: Microsoft Edge
- Version: 124.0.2478.105

**Comment by Classsic36** [comment]
Also having this issue with Chrome 125.0.6422.60 and Edge 125.0.2535.51, both running OTD v3.6.2 & BTD v4.11.3.

Strangely, it was working fine for me until an hour or two ago. I guess Twitter did something on their side?

EDIT: Seems to be working again

**Comment by WhereTheTimeWent** [comment]
Chrome 125.0.6422.61

I installed BTD v4.11.3 2h after it was released yesterday. It hasn't worked then and it's still not working for me.
I also removed it from Chrome and added it again - same issue.
I tried to reproduce in a fresh Chrome profile, but couldn't login to OTD (seems like https://github.com/dimdenGD/OldTweetDeck/issues/240).

This pops up every 1-2 seconds in DevTools:

![image](https://github.com/dimdenGD/BetterTweetDeck/assets/64332179/8fe25dee-9e5b-4013-aa73-9bf671acb3d4)

It worked fine until they switched to x.com.

**Comment by WhereTheTimeWent** [comment]
> It hasn't worked then and it's still not working for me.

Update: Saw in another issue that you have to replace https://twitter.com/i/tweetdeck with https://x.com/i/tweetdeck (makes sense). After I did that, I imported state of OTD and settings of BTD - now it works again (after Ctrl+Shift+R, didn't load the first time).

So, how I got it working:
- Open https://twitter.com/i/tweetdeck
- Login
- Open https://x.com/i/tweetdeck
- Press Ctrl+Shift+R if it doesn't load
- You're in

I cleared cache and cookies in my usual Chrome profile, imported OTD state and BTD settings (saved both earlier) and now OTD and BTD are working again.

**Comment by Dajova** [comment]
> > It hasn't worked then and it's still not working for me.
> 
> Update: Saw in another issue that you have to replace https://twitter.com/i/tweetdeck with https://x.com/i/tweetdeck (makes sense). After I did that, I imported state of OTD and settings of BTD - now it works again (after Ctrl+Shift+R, didn't load the first time).
> 
> So, how I got it working:
> 
>     * Open https://twitter.com/i/tweetdeck
> 
>     * Login
> 
>     * Open https://x.com/i/tweetdeck
> 
>     * Press Ctrl+Shift+R if it doesn't load
> 
>     * You're in
> 
> 
> I cleared cache and cookies in my usual Chrome profile, imported OTD state and BTD settings (saved both earlier) and now OTD and BTD are working again.

This method does not seem to work on Firefox, i just keep on getting the same error that you mentioned above and claims that the page doesn't exist.
![image](https://i.imgur.com/w7n84dB.png)

**Comment by WhereTheTimeWent** [comment]
> This method does not seem to work on Firefox

Have you cleared cache and cookies? This only worked for me in a fresh profile or when I cleared cache and cookies.
Make sure to backup your OTD state / config in OTD settings, otherwise that's gone after clearing cache and cookies.

**Comment by Mara-Li** [comment]
Hi
I tried cookie, cleaning OTD (deleting etc) but it doesn't works :( (using Firefox)

**Comment by Dajova** [comment]
> > This method does not seem to work on Firefox
> 
> Have you cleared cache and cookies? This only worked for me in a fresh profile or when I cleared cache and cookies. Make sure to backup your OTD state / config in OTD settings, otherwise that's gone after clearing cache and cookies.

Yes, several times. Refuses to redirect to the deck at al. All it did was to expand the error message:
![image](https://i.imgur.com/SvIMIxG.png)

**Comment by Mara-Li** [comment]
I fixed this with reinstalling old tweetdeck + bettertweetdeck!

**Comment by Dajova** [comment]
> I fixed this with reinstalling old tweetdeck + bettertweetdeck!

yeah, dunno what to tell you. fresh install of extensions and cleared everything...
![image](https://i.imgur.com/dLxGmDw.png)

**Comment by Mara-Li** [comment]
I also cleaned my cache multiple time… I dunno why do you still have the bug and not me :<

**Comment by Dajova** [comment]
Alright, NOW it works... I think it was a oldtweetdeck issue, as they recently released a new version and that seemed to have fixed it. https://github.com/dimdenGD/OldTweetDeck/releases/tag/v3.6.4

**Comment by staticanimal** [comment]
unhelpful solution unfortunately but i was ultimately able to solve this issue by simply switching the browser i ran the extension in from edge to firefox developer edition

**Comment by RdNetwork** [comment]
Having the same issue now with OldTweetdeck 4.0.2. 
Doesn't seem to go away with reloads unfortunately...

EDIT: extension (sometimes) loads when loading using https://twitter.com/i/tweetdeck but not from https://x.com/i/tweetdeck or https://tweetdeck.twitter.com but it's very inconsistent
