### ISSUE TITLE
Search columns take hours to populate

### ISSUE THREAD

**Issue by snowbound** [dimdenGD/BetterTweetDeck#5]
**Describe the bug**
When browser is open and Bettertweet loads the 2 search columns do not populate until  hours later

**To Reproduce**

1. Shutdown computer for nite
2. Start computer up next day and open Brave. Restore open tabs from last session
3. All columns load except for 2 search columns which just have spinning circles

**Expected behavior**
Search columns should populate

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] Windows10 22H2
- Browser [e.g. chrome, safari] Brave 
- Version [e.g. 22] Beta Version 1.58.106 

**Additional context**

**Comment by dimdenGD** [comment]
This is not related to BetterTD but OldTweetDeck, also you're getting rate limit error
